/**
 * Phase 27-1: TypeScript SDK Generator
 * Generates TypeScript client library from OpenAPI spec
 */

import { generateOpenAPISpec, OpenAPISpec } from './openapi-spec';

export interface SDKConfig {
  packageName: string;
  version: string;
  author: string;
  license: string;
}

export class TypeScriptSDKGenerator {
  private spec: OpenAPISpec;
  private config: SDKConfig;

  constructor(config: SDKConfig = TypeScriptSDKGenerator.defaultConfig()) {
    this.spec = generateOpenAPISpec();
    this.config = config;
  }

  static defaultConfig(): SDKConfig {
    return {
      packageName: '@freelang/oauth2-sdk',
      version: '2.1.0',
      author: 'FreeLang Team',
      license: 'MIT',
    };
  }

  /**
   * Generate complete SDK package
   */
  generateSDK(): SDKPackage {
    return {
      packageJson: this.generatePackageJson(),
      tsconfig: this.generateTsConfig(),
      client: this.generateClient(),
      types: this.generateTypes(),
      index: this.generateIndex(),
      README: this.generateREADME(),
    };
  }

  /**
   * Generate package.json
   */
  private generatePackageJson(): string {
    return JSON.stringify(
      {
        name: this.config.packageName,
        version: this.config.version,
        description: 'FreeLang OAuth2 SDK - Strongly typed client for authentication',
        main: 'dist/index.js',
        types: 'dist/index.d.ts',
        scripts: {
          build: 'tsc',
          test: 'jest',
          'test:watch': 'jest --watch',
          lint: 'eslint src/**/*.ts',
          prepublish: 'npm run build',
        },
        keywords: ['oauth2', 'authentication', 'freeLang', 'social-login'],
        author: this.config.author,
        license: this.config.license,
        dependencies: {
          'node-fetch': '^3.0.0',
        },
        devDependencies: {
          typescript: '^5.0.0',
          jest: '^29.0.0',
          '@types/jest': '^29.0.0',
          '@types/node': '^18.0.0',
          eslint: '^8.0.0',
          '@typescript-eslint/eslint-plugin': '^5.0.0',
          '@typescript-eslint/parser': '^5.0.0',
        },
        repository: {
          type: 'git',
          url: 'https://github.com/freelang/sdk-ts',
        },
        bugs: {
          url: 'https://github.com/freelang/sdk-ts/issues',
        },
        homepage: 'https://github.com/freelang/sdk-ts',
      },
      null,
      2
    );
  }

  /**
   * Generate tsconfig.json
   */
  private generateTsConfig(): string {
    return JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          module: 'commonjs',
          lib: ['ES2020'],
          declaration: true,
          declarationMap: true,
          sourceMap: true,
          outDir: './dist',
          rootDir: './src',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          noImplicitAny: true,
          strictNullChecks: true,
          strictFunctionTypes: true,
          noImplicitThis: true,
          alwaysStrict: true,
        },
        include: ['src/**/*.ts'],
        exclude: ['node_modules', 'dist', '**/*.test.ts'],
      },
      null,
      2
    );
  }

  /**
   * Generate types.ts with all request/response interfaces
   */
  private generateTypes(): string {
    const schemas = this.spec.components.schemas;
    let typesCode = `/**
 * Auto-generated TypeScript types from OpenAPI spec
 * Generated by Phase 27-1 SDK Generator
 */

`;

    // Generate interfaces for each schema
    for (const [name, schema] of Object.entries(schemas)) {
      typesCode += this.generateInterface(name, schema);
      typesCode += '\n\n';
    }

    return typesCode;
  }

  /**
   * Generate TypeScript interface from schema
   */
  private generateInterface(name: string, schema: any): string {
    let code = `export interface ${name} {`;

    if (schema.properties) {
      for (const [propName, propSchema] of Object.entries(schema.properties)) {
        const required = schema.required?.includes(propName) ? '' : '?';
        const type = this.getTypeScriptType(propSchema);
        code += `\n  ${propName}${required}: ${type};`;
      }
    }

    code += '\n}';
    return code;
  }

  /**
   * Convert JSON schema type to TypeScript type
   */
  private getTypeScriptType(schema: any): string {
    if (schema.$ref) {
      return schema.$ref.split('/').pop()!;
    }

    if (schema.oneOf) {
      return schema.oneOf.map((s: any) => this.getTypeScriptType(s)).join(' | ');
    }

    if (schema.enum) {
      return schema.enum.map((e: any) => `'${e}'`).join(' | ');
    }

    if (schema.type === 'array') {
      return `${this.getTypeScriptType(schema.items)}[]`;
    }

    switch (schema.type) {
      case 'string':
        return schema.format === 'date-time' ? 'Date' : 'string';
      case 'integer':
        return 'number';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'object':
        return 'Record<string, any>';
      default:
        return 'any';
    }
  }

  /**
   * Generate main client class
   */
  private generateClient(): string {
    const authorizePath = this.spec.paths['/oauth2/authorize']?.get;
    const tokenPath = this.spec.paths['/oauth2/token']?.post;
    const revokePath = this.spec.paths['/oauth2/revoke']?.post;
    const mePath = this.spec.paths['/api/me']?.get;
    const unlinkPath = this.spec.paths['/api/account/unlink']?.post;

    return `/**
 * Auto-generated FreeLang OAuth2 TypeScript Client
 * Generated by Phase 27-1 SDK Generator
 */

import fetch from 'node-fetch';
import * as Types from './types';

export interface ClientConfig {
  baseURL?: string;
  timeout?: number;
  headers?: Record<string, string>;
}

export class FreeLangOAuth2Client {
  private baseURL: string;
  private timeout: number;
  private headers: Record<string, string>;
  private accessToken?: string;

  constructor(config: ClientConfig = {}) {
    this.baseURL = config.baseURL || 'https://api.freelang.dclub.kr';
    this.timeout = config.timeout || 30000;
    this.headers = {
      'Content-Type': 'application/json',
      ...config.headers,
    };
  }

  /**
   * Set access token for authenticated requests
   */
  setAccessToken(token: string): void {
    this.accessToken = token;
  }

  /**
   * GET /oauth2/authorize - Get authorization URL
   */
  async authorize(provider: 'google' | 'github'): Promise<string> {
    const response = await this.request('GET', '/oauth2/authorize', {
      provider,
    });

    if (response.redirectUrl) {
      return response.redirectUrl;
    }

    throw new Error('No redirect URL returned');
  }

  /**
   * POST /oauth2/token - Exchange code for token or refresh token
   */
  async token(request: Types.TokenRequest): Promise<Types.TokenResponse> {
    const response = await this.request('POST', '/oauth2/token', request);

    if (response.access_token) {
      this.accessToken = response.access_token;
    }

    return response as Types.TokenResponse;
  }

  /**
   * POST /oauth2/revoke - Revoke a token
   */
  async revoke(request: Types.RevokeRequest): Promise<{ success: boolean }> {
    return this.request('POST', '/oauth2/revoke', request);
  }

  /**
   * GET /api/me - Get current user profile
   */
  async getMe(): Promise<Types.UserProfile> {
    return this.request('GET', '/api/me', undefined, true) as Promise<Types.UserProfile>;
  }

  /**
   * POST /api/account/unlink - Unlink social account
   */
  async unlinkAccount(request: Types.UnlinkRequest): Promise<Types.UnlinkResponse> {
    return this.request('POST', '/api/account/unlink', request, true) as Promise<Types.UnlinkResponse>;
  }

  /**
   * GET /oauth2/health - Check server health
   */
  async health(): Promise<Types.HealthResponse> {
    return this.request('GET', '/oauth2/health') as Promise<Types.HealthResponse>;
  }

  /**
   * Internal HTTP request method
   */
  private async request(
    method: string,
    path: string,
    body?: any,
    requiresAuth: boolean = false
  ): Promise<any> {
    const url = \`\${this.baseURL}\${path}\`;

    const options: any = {
      method,
      headers: { ...this.headers },
      timeout: this.timeout,
    };

    if (requiresAuth) {
      if (!this.accessToken) {
        throw new Error('Access token required but not set');
      }
      options.headers['Authorization'] = \`Bearer \${this.accessToken}\`;
    }

    if (body && (method === 'POST' || method === 'PUT')) {
      options.body = JSON.stringify(body);
    }

    const response = await fetch(url, options);

    if (!response.ok) {
      const error = await response.json() as any;
      throw new Error(error.error_description || error.error || 'Unknown error');
    }

    if (response.status === 204) {
      return { success: true };
    }

    return response.json();
  }
}

export default FreeLangOAuth2Client;
`;
  }

  /**
   * Generate index.ts (entry point)
   */
  private generateIndex(): string {
    return `/**
 * FreeLang OAuth2 SDK Entry Point
 */

export { FreeLangOAuth2Client } from './client';
export * as Types from './types';
export { generateOpenAPISpec } from '../sdk/openapi-spec';
`;
  }

  /**
   * Generate README.md with usage examples
   */
  private generateREADME(): string {
    return `# FreeLang OAuth2 SDK (TypeScript)

Strongly typed TypeScript client for FreeLang OAuth2 authentication API.

## Installation

\`\`\`bash
npm install @freelang/oauth2-sdk
\`\`\`

## Quick Start

### Initialize Client

\`\`\`typescript
import { FreeLangOAuth2Client } from '@freelang/oauth2-sdk';

const client = new FreeLangOAuth2Client({
  baseURL: 'https://api.freelang.dclub.kr',
  timeout: 30000,
});
\`\`\`

### Get Authorization URL

\`\`\`typescript
// Get Google authorization URL
const googleAuthUrl = await client.authorize('google');

// Redirect user to Google
window.location.href = googleAuthUrl;
\`\`\`

### Exchange Code for Token

\`\`\`typescript
// After user returns from OAuth provider
const tokenResponse = await client.token({
  grant_type: 'authorization_code',
  code: authorizationCode,
  client_id: 'your-client-id',
  client_secret: 'your-client-secret',
  redirect_uri: 'https://yourapp.com/callback',
  code_verifier: pkceCodeVerifier,
});

// Client automatically sets access token
\`\`\`

### Get User Profile

\`\`\`typescript
const profile = await client.getMe();
console.log(profile.email, profile.name);
\`\`\`

### Manage Account Linking

\`\`\`typescript
// Unlink a social provider
await client.unlinkAccount({
  provider: 'google',
});

// Get updated profile
const updated = await client.getMe();
\`\`\`

### Refresh Token

\`\`\`typescript
const newToken = await client.token({
  grant_type: 'refresh_token',
  refresh_token: oldRefreshToken,
  client_id: 'your-client-id',
  client_secret: 'your-client-secret',
});
\`\`\`

### Revoke Token

\`\`\`typescript
await client.revoke({
  token: accessToken,
  client_id: 'your-client-id',
  client_secret: 'your-client-secret',
});
\`\`\`

## Type Definitions

All request/response types are fully typed:

\`\`\`typescript
import { Types } from '@freelang/oauth2-sdk';

const profile: Types.UserProfile = await client.getMe();
const accounts: Types.SocialAccount[] = profile.socialAccounts;
\`\`\`

## API Reference

### authorize(provider)
Initiates OAuth2 flow for specified provider.

**Parameters:**
- \`provider\`: 'google' | 'github'

**Returns:** \`Promise<string>\` - Authorization URL

### token(request)
Exchanges authorization code or refresh token for access token.

**Parameters:**
- \`request\`: \`TokenRequest\` with grant_type, code/refresh_token, client credentials

**Returns:** \`Promise<TokenResponse>\` - Token response with access_token

### getMe()
Gets current authenticated user profile.

**Returns:** \`Promise<UserProfile>\`

### unlinkAccount(request)
Unlinks a social provider from user account.

**Parameters:**
- \`request\`: \`UnlinkRequest\` with provider

**Returns:** \`Promise<UnlinkResponse>\`

### revoke(request)
Revokes an access or refresh token.

**Parameters:**
- \`request\`: \`RevokeRequest\` with token and client credentials

**Returns:** \`Promise<{success: boolean}>\`

## Error Handling

\`\`\`typescript
try {
  const profile = await client.getMe();
} catch (error) {
  if (error.message.includes('unauthorized')) {
    // Handle 401 - token expired or invalid
  } else {
    // Handle other errors
  }
}
\`\`\`

## RFC Compliance

- RFC 6749 (OAuth 2.0 Authorization Framework)
- RFC 7636 (PKCE - Proof Key for Code Exchange)
- RFC 7009 (Token Revocation)

## License

${this.config.license}

## Support

For issues and feature requests, visit: https://github.com/freelang/sdk-ts
`;
  }
}

export interface SDKPackage {
  packageJson: string;
  tsconfig: string;
  client: string;
  types: string;
  index: string;
  README: string;
}
